PATH: ""

BACTERIA:

REPRESENTATION:

LABEL_TYPE:

METHODS: ["LR_l1"]

OPTIMIZATION:

# LABEL: Susceptibility # 'Susceptibility' or 'MIC'

# OPTIMIZATION: RandomizedSearchCV # 'GridSearchCV', 'RandomizedSearchCV', 'BayesSearchCV' and "none"
