#PATH_DATA: "/mnt/c/Users/Fernando/Documents/Project_2/Pipeline_dataset"
PATH_DATA: "/rds/general/user/fg520/home/Project2/pipeline_dataset" # specifiy path to folder where data is stored (only folder name, no / afterwards)

BACTERIA: ["mtb"]

#OUTPUT_DIR: "/mnt/c/Users/Fernando/Documents/Project_2/output"
OUTPUT_DIR: "/rds/general/user/fg520/home/Project2/output"

REPRESENTATION: ["gene_presence_absence"] # 'snps', 'gene_presence_absence'

# LABEL_TYPE: Susceptibility # 'Susceptibility' or 'MIC'

DRUGS: ["ciprofloxacin", "moxifloxacin"]

METHODS: ["LR_l1", "LR_l2"]

OPTIMIZATION: GridSearchCV # 'GridSearchCV', 'RandomizedSearchCV', 'BayesSearchCV' and "none"