# PATH_DATA: "/rds/general/user/ns1920/projects/bacterial_datasets/live/pipeline_data" # specifiy path to folder where data is stored (only folder name, no / afterwards)
PATH_DATA: "/mnt/c/Users/Fernando/Documents/Project_2/Pipeline_dataset"

BACTERIA: ["test_bacterium"]

OUTPUT_DIR: ""

REPRESENTATION: ["gene_presence_absence"] # 'snps', 'gene_presence_absence'

OPTIMIZATION: RandomizedSearchCV # 'GridSearchCV', 'RandomizedSearchCV', 'BayesSearchCV' and "none"

# LABEL_TYPE: Susceptibility # 'Susceptibility' or 'MIC'

METHODS: ["LR_l1", "LR_l2", "SVM_l1", "INGOT"]

OPTIMIZATION: GridSearchCV # 'GridSearchCV', 'RandomizedSearchCV', 'BayesSearchCV' and "none"