PATH_DATA: "/rds/general/user/ns1920/projects/bacterial_datasets/live/pipeline_data" # specifiy path to folder where data is stored (only folder name, no / afterwards)

BACTERIA: ["test_bacterium"]

OUTPUT_DIR: "/rds/general/user/ns1920/projects/bacterial_datasets/ephemeral/pipeline_output/test_bacterium"

REPRESENTATION: ["gene_presence_absence"] # 'snps', 'gene_presence_absence'

MODE: "MIC" # "Classification"

DRUGS: ["amikacin"]

METHODS: ["LinR", "LinR_l1", "LinR_l2", "LinR_elasticnet", "SVMR"] #Classification ["LR_l1", "LR_l2", "LR_elasticnet", "SGD_l1", "SGD_l2", "SGD_elasticnet", "DT", "RF", "ET", "ADB", "GBT", "GNB", "CNB", "SVM_l1", "SVM_l2", "KNN"]

OPTIMIZATION: 'None' # 'GridSearchCV', 'RandomizedSearchCV', 'BayesSearchCV' and "none"