#PATH_DATA: "/mnt/c/Users/Fernando/Documents/Project_2/Pipeline_dataset"
PATH_DATA: "/rds/general/user/fg520/home/Project2/pipeline_dataset" # specifiy path to folder where data is stored (only folder name, no / afterwards)

#BACTERIA: ["test_bacterium"]
BACTERIA: ["mtb"]

#OUTPUT_DIR: "/mnt/c/Users/Fernando/Documents/Project_2/output"
OUTPUT_DIR: "/rds/general/user/fg520/home/Project2/output"

REPRESENTATION: ["gene_presence_absence"] # 'snps', 'gene_presence_absence'

# LABEL_TYPE: Susceptibility # 'Susceptibility' or 'MIC'

DRUGS: ["amikacin", "capreomycin", "ciprofloxacin", "ethambutol", "ethionamide", "isoniazid", "kanamycin", "moxifloxacin", "ofloxacin", "pyrazinamide", "rifampicin", "streptomycin"]

METHODS: ["LR_elasticnet", "SGD_l1", "SGD_l2", "SGD_elasticnet", "DT", "RF", "ET", "ADB", "GBT", "SVM_l1", "KNN"]

OPTIMIZATION: GridSearchCV # 'GridSearchCV', 'RandomizedSearchCV', 'BayesSearchCV' and "none"