PATH: ""

BACTERIA:

REPRESENTATION:

# LABEL_TYPE: Susceptibility # 'Susceptibility' or 'MIC'

METHODS: ["LR_l1", "SVM_l1"]

OPTIMIZATION: GridSearchCV # 'GridSearchCV', 'RandomizedSearchCV', 'BayesSearchCV' and "none"