PATH_DATA: "/rds/general/user/ns1920/projects/bacterial_datasets/live/pipeline_data" # specifiy path to folder where data is stored (only folder name, no / afterwards)

BACTERIA: ["test_bacterium", "s_pyogenes"]

REPRESENTATION: ["snps"] # 'snps', 'gene_presence_absence'

LABEL_TYPE: ["tbd"]

METHODS: ["LR_l1"]

OPTIMIZATION: RandomizedSearchCV # 'GridSearchCV', 'RandomizedSearchCV', 'BayesSearchCV' and "none"

# LABEL: Susceptibility # 'Susceptibility' or 'MIC'

